- CHANGELOG.md
- hubl_snippets_gen.py
- package.json
- snippets/auto_gen/hubl_tags.json
This is to better support https://github.com/williamspiro/HubL-Language-Extension/issues/6. 
Right now, HubL with an end tag (not self closed) and has a snippet, gets the straight snippet dump, rather than a parameter formatted snippet. 
This could still be handled better, but is a good start
> Support HubL which has a closing tag

- CONTRIBUTING.md
- LICENSE
- README.md
- package.json
After merging, we'll need to:
- update this repo name (to `hubspot-cms-vscode`)
- build/publish the [extension to the marketplace](https://code.visualstudio.com/api/working-with-extensions/publishing-extension)
Resolves #58 
Resolves #46
> Update extension info for launch

- snippets/man_gen/hubl_custom_module_fields.json
This PR does the following:
1. Removes the workflow field
2. Removes `id` property from field snippets
3. Tightens up the descriptions to make them shorter and more general since they can be used for themes and modules
Fixes #64
@williamspiro @miketalley
> Improve field snippets

- README.md
- Fix the `*.css` file association typo at line 17 and improve markdown.
- Change markdown style at line 30 to match the markdown used at line 13.
> Fix typo and improve markdown.

- snippets/man_gen/hubl_custom_module_fields.json
Adds in missing comma: 
Fixes #90
> Fix typo in group snippet

- scripts/generate.js
- snippets/auto_gen/hubl_expTests.json
- snippets/auto_gen/hubl_filters.json
- snippets/auto_gen/hubl_functions.json
- snippets/auto_gen/hubl_tags.json
Changes snippet quotes from double to single to match up with the [CMS Boilerplate Styleguide](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/STYLEGUIDE.md)
Fixes #85
> Switch snippets to single quotes

- README.md
Adds a common issue entry to give some guidance for users that would like to enable emmet in their HTML+HUBL Files
I looked into programmatic ways of handling this, but there really isn't a great solution. I also referenced other template language extensions and documenting the configuration seems common.
Fixes #87
> Add emmet info

- package.json
- scripts/generate.js
- snippets/auto_gen/hubl_tags.json
- snippets/man_gen/default_modules.json
Adds more robust, nestable dnd area tag snippets to make authoring DND areas quicker.
A WIP example:
> Add better DND area snippets

- index.js
- lib/constants.js
- lib/notify.js
To spread awareness of Beta Features, this adds a notification that shows up for users to alert them of the new feature. Adds a button so that they can opt in without visiting settings.
Note: VSCode doesn't seem to allow any styling (or even new lines) in messages.
> Show notification to user if Beta hasn't been enabled

- langconfig/hubl-html-language-configuration.json
> Fix `cmd+/` comment shortcut

- snippets/man_gen/hubl_custom_module_fields.json
Adds snippets for new style fields. These snippets do not include examples of the default property since these fields are meant to typically be used as overrides, rather than the source of truth for a style.
> add style field snippets

- package-lock.json
- package.json
- src/index.ts
- src/lib/constants.js
Removes the existing `hubspot.beta` setting and introduces `hubspot.hublLinting`, which is turned on by default.
> Move hubl linting out of beta

- package-lock.json
- package.json
- src/lib/validation.js
Different validations apply to different template types. This PR allows parses the filepath and annotations (if they exist) to pass extra context along to the validate endpoint.
Note: this relies on future additions to cli-lib
> Pass template context to validate

- package-lock.json
- package.json
- src/lib/validation.js
In the current build, the HubL linting feature falls over due to regression in `cli-lib` [that has been fixed](https://github.com/HubSpot/hubspot-cli/pull/770). 
This also bumps the version of cli-lib to ^4 while we're at it.
> Update cli-lib and pick up fix for template annotation parse regression

- .vscodeignore
- package-lock.json
- package.json
Cuts the bundle size down from >4k files (14mb) to 38 files (1.5mb)
> Don't package node_modules folder

- src/extension.ts
- src/lib/commands.ts
- src/lib/commands/auth.ts
- src/lib/helpers.ts
- src/lib/uri.ts
Fixes #151 
Related Info
https://code.visualstudio.com/api/references/vscode-api#window.registerUriHandler
> Uri handler multiple windows

- src/lib/validation.ts
When referencing a file within the same directory by relative path, the extension was incorrectly presenting an error that the file could not be found:
If you notice, the file BE assumes that this path is at the root level because we're not passing a `template_path` value along with the file source.
This PR adds that `template_path`, so all file paths returned from the BE are not absolute paths based on the user's local FS. This doesn't affect any linting on the BE and let's the extension do a proper check to see if the file exists:
> Fix bug when resolving shallow relative paths

- .github/workflows/build.yml
The github build action is encountering an error...
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/setup-node@v1
```
This updates the node version to 16 to fix this.
EDIT: Also switched to using `npm` from `yarn`
> Updated node version when running github build action

- package.json
- src/extension.ts
I noticed an error if you opened VS Code with no active folders:
After this change the extension will not initialize or show the `ActivityBar` if there is no open folder/file:
> Don't enable extension if workspace is empty

- package.json
- src/lib/fileHelpers.ts
The assets needed to populate a created module are not available as part of the webpack bundle.
`@hubspot/cli-lib/defaults/Sample.module/...`
This PR works alongside a PR to the CLI (https://github.com/HubSpot/hubspot-cli/pull/792) that will move assets to a new package and create helper functions to download files from that package on github.
/cc @anthmatic @jsines @TanyaScales
> Module creation fix

- .gitignore
- .prettierignore
- .vscodeignore
- package-lock.json
- package.json
- test/specs/example.e2e.ts
- test/tsconfig.json
- wdio.conf.ts
Tests can be run with `npm run test:e2e`, currently only contains tests for if VSCode opened and if the extension loaded into the Activity Bar.
I enabled `this.retries(3)` because the test was running before the extension loaded and `this.timeout(n)` wouldn't seem to fix it. It passes the second time. Not sure if there's a way to hide the retried test's failure from the report.
WDIO docs: https://webdriver.io/docs/wdio-vscode-service/
~~Also the build is failing with:
`error @wdio/cli@8.1.2: The engine "node" is incompatible with this module. Expected version "^16.13 || >=18". Got "12.22.12"`
Could we just change the node version in build.yml? I see we're also mixing package managers in there so it's pretty out of date haha~~
> Testing infra

- package.json
- src/extension.ts
- src/lib/commands.ts
- src/lib/helpers.ts
The extension `activitybar` item was disabled when no workspace folder is open (`!workbench.explorer.emptyView.active`). This PR allows the extension to be activated and opened and adds a notification section to notify the user that they need to open a folder.
The content of the section mimics the one displayed in the `explorer` activity bar item provided with VSCode. The "Open Folder" button opens the file picker and reloads the extension when a folder is selected/opened. The "Clone Repository" button runs the "Git: Clone"(`git.clone`) command, which will allow a repository to be opened instead.
_Note:_ The ability to mirror the `workbench.explorer.emptyView` by embedding it into our menu does not work. I filed a bug for this in vscode -> https://github.com/microsoft/vscode/issues/171859 …
> Extension can be activated and opened when no workspace folder is open

- src/lib/validation.ts
> Fix type that caused preventing sending template type with HubL Validation request

- package.json
- src/lib/commands/terminal.ts
If the old cms-cli was already installed on a user's machine, and the extension runs npm commands to install hubspot-cli, npm will crash in the process because it will not overwrite the existing executable without --force.
This change adds a command to remove the legacy CLI during the update process to prevent this error.
> Prevent error if hs already exists in the user's bin

- CHANGELOG.md
- package.json
- src/lib/commands/terminal.ts
- src/lib/fileHelpers.ts
- src/lib/helpers.ts
- src/lib/tracking.ts
Updates terminal usage and paths for win32 compatibility. 
Also updates tracking to be non-blocking, no longer `await`s it and instead just reports an error when the promise finishes if it fails.
> Win32 fixes

- package-lock.json
- package.json
- src/lib/commands/remoteFs.ts
- src/lib/constants.ts
Adds fetch command to remote file system view items on right-click: 
Which proceeds to open a dialog window to select a location to save the remote file to the local filesystem: 
When a file is fetched, it will be downloaded to the selected folder.
When a folder is fetched, _it's contents_ will be downloaded to the selected folder. To duplicate a remote folder to the local filesystem, a new folder must be created to store its contents. This behavior is a little quirky, I might play around a bit more and see if we can get it to download the folder itself without needing the user to type in their own file name, but the CLI fetch requires a specificed file path destination as well so the behavior isn't _super_ out of the norm.
> remotefs fetch

- package.json
- src/lib/commands/remoteFs.ts
- src/lib/constants.ts
- src/lib/providers.ts
- src/lib/providers/remoteFsProvider.ts
Working on upload (& got it working pretty well!) but got frustrated by the amount of hard refreshes the remote filesystem view had to do to keep it in sync locally. This should cut back pretty hard on the amount of API calls necessary to keep the system in sync, especially as the amount of files shown in the view grows. Instead of firing a request of every remote folder on refresh (fetch '/', then all children of '/' that are open, then all their children, etc) we store the results and invalidate the parent whenever a file gets deleted. Works much nicer!
> Cache remote files

- package.json
- src/lib/commands/remoteFs.ts
- src/lib/constants.ts
- src/lib/helpers.ts
- src/lib/providers.ts
- src/lib/providers/remoteFsProvider.ts
Adds watch functionality to VSCE. Similar to upload, watch can be initiated either via right-click on the desired folder in the explorer, or via the dropdown context in the remote FS view. The user will then be prompted for the remote path with which to sync.
The synced folder is then given a special icon in the remote FS view, and the watch session can be cancelled with a right click action, or by initiating another session. Only one watch session can be active at a time.
Changes to the local filesystem are watched using `chokidar` in `cli-lib`, and a special event is added for VSCE to invalidate the remote FS cache when files are removed, added, or moved.
> Remote FS Watch

- src/lib/commands/config.ts
- src/lib/commands/remoteFs.ts
- src/lib/constants.ts
- src/lib/providers/remoteFsProvider.ts
See title! Some of these `hubspot.remoteFs.refresh`s should be hard refreshes, they were just put in before there was a cache so there was no distinction, went ahead and switched them over. Also removed some unused imports and added tracking for basic remoteFs events.
> Clean up commands to consts, add tracking, refresh remotefs on default account change

- package.json
- src/lib/commands/remoteFs.ts
- src/lib/providers/remoteFileProvider.ts
- src/lib/providers/remoteFsProvider.ts
- src/lib/types.ts
Adds @hubspot folder to the remote FS view. Always appears at the top of the root directory with a locked icon. Contents are split between themes and modules and sorted, the same way they appear in the Design Manager.
Also did some refactoring of the tree building code to hopefully make it a little easier to read. FileLinks are now just the logical aspect of the file / path and its properties, and all decorative / presentation stuff is in the RemoteFsTreeItem constructor. Feels much nicer that way!
> Add @hubspot folder to remote FS view

- package.json
- src/lib/providers/remoteFileProvider.ts
Changes RFS view name to better signify that it belongs to the account selected as default
Adds a header to remote files when viewed to better signify that they're read-only (Thanks for the suggestion bmatto!)
> Minor copy and rfs display changes

- src/extension.ts
- src/lib/commands/remoteFs.ts
- src/lib/logger.ts
Now overrides the [cli-lib logger ](https://github.com/HubSpot/hubspot-cli/blob/8aafada9270602e912d89fc6a513816f5f7232bb/packages/cli-lib/logger.js#L32) to instead surface the error messages within the VSCode window. Also adds a catch/finally to delete function to not break if an error occurs.
> Logger override, add error catch for delete 

- snippets/man_gen/hubl_custom_module_fields.json
Add `validation_error_message` to text field snippet in `snippets/man_gen/hubl_custom_module_fields.json`
> fixes #122 – adds validation_error_message to text

- package-lock.json
- package.json
- scripts/generate.js
- snippets/auto_gen/hubl_tags.json
This is just a redo of #160 in order to get rid of conflicts and issues with my machine. I double checked the JinjavaDocFactory work that Anthony did in January to make sure the snippets were corrected, and they were. We should be safe to integrate this new functionality into the autogeneration of HubL tags.
> Support codeSnippets from BE

- src/lib/providers/remoteFsProvider.ts
Resolves https://github.com/HubSpot/hubspot-cms-vscode/issues/248
Minor oversight! We sort default directory contents when we split between themes & modules like we do in DMUI. But we don't sort the rest of the remote directory contents. This fixes that! 
Waiting to ship this out until after INBOUND.
> Sort remote directory alphabetically

- README.md
- syntaxes/hubl.json
Context: Issue #257 
The token `is not` was being incorrectly captured in our syntax. This PR updates the syntax regex to correctly capture this token. Here is a test snippet from the original issue, and the updated syntax highlighting:
```html
<div>
{%- if classes and (classes is string) -%}
{% set classes = classes|split(" ") %}
{%- elif (classes is not string) and not (classes is string) or not foo -%}
{% set classes = classes|split(",") %}
{%- elif (classes is not string) and (classes is not iterable) or not foo -%}
{% set classes = [] %}
{%- endif -%}
</div>
```
> Fix `is not` syntax highlighting

- package-lock.json
- package.json
Tested a bit and there don't seem to be any regressions (and if it's properly following semver there shouldn't be since this is a minor version diff `1.3.0 -> 1.13.1`)
Bumping LDL seems to fix trackUsage on its own; I'm still not quite sure the exact cause but there's a slightly updated implementation of trackUsage on their end that fixes it.
> 1.13.1 to fix trackUsage

- package-lock.json
- package.json
- src/lib/auth.ts
- src/lib/commands/account.ts
- src/lib/commands/config.ts
- src/lib/commands/remoteFs.ts
- src/lib/constants.ts
- src/lib/helpers.ts
- src/lib/providers/remoteFileProvider.ts
- src/lib/providers/remoteFsProvider.ts
- src/lib/providers/treedata/accounts.ts
- src/lib/statusBar.ts
- src/lib/tracking.ts
- src/lib/types.ts
- src/lib/uri.ts
- src/lib/validation.ts
This PR needs to be merged before the PR to add JSON schema validation to the extension: #280 
In the schema validation PR, we need to bump the `@hubspot/local-dev-lib` package version to `^3.1.0` to be compatible with the new dependency `@hubspot/project-parsing-lib` library which also contains LDL as a dependency. 
There are significant differences between the two versions of LDL, and so I've made updates to the code where needed. 
**IMPORTANT NOTE PLEASE READ:**
Some imports from `@hubspot/local-dev-lib` **must** keep CommonJS syntax. This is because:
1. In `@hubspot/local-dev-lib`, the `exports` field in the `package.json` file exports the `lib` folder like this:
```
"./*": "./lib/*.js"
```
2. Only ES modules can read the `exports` field.
3. VSCode extensions **don't support ES …
> Bump LDL version & update imports

- package-lock.json
- package.json
- src/lib/auth.ts
- src/lib/commands/account.ts
- src/lib/commands/config.ts
- src/lib/helpers.ts
- src/lib/providers/treedata/accounts.ts
- src/lib/statusBar.ts
- src/lib/uri.ts
This leverages all the utils from LDL that help with global config compatibility. The tldr is that we shouldn't directly reference `portalId` or `defaultAccount` anymore.
I also made a fix to the account delete and rename actions. They work correctly, but they weren't refreshing the accounts section after performing the updates which makes it look like it isn't working.
> Update VS code to be compatible with the global config
