HubSpot/hubspot-cms-vscode

- README.md
- hubl_snippets_gen.py
- package.json
- snippets/hubl_expTests.json
- snippets/hubl_filters.json
- snippets/hubl_functions.json
- snippets/hubl_tags.json
Refactors the Python script to be more modular. Adds expression tests
> Python refactor

- hubl_snippets_gen.py
- snippets/auto_gen/hubl_functions.json
Adds support for `crm_object` HubL Snippet
> `crm_object` auto-gen snippet update

- README.md
- package.json
- snippets/man_gen/hubl_custom_module_fields.json
Added all available fields as well as groups and repeater.
> Added Custom Field field.json snippets

- hubl_snippets_gen.py
- package.json
- snippets/auto_gen/hubl_expTests.json
- snippets/auto_gen/hubl_filters.json
- snippets/auto_gen/hubl_functions.json
- snippets/auto_gen/hubl_tags.json
Updates after changes from https://github.com/HubSpot/jinjava/pull/289
Also adds some new filters and removes some functions
> auto-gen update

- snippets/man_gen/hubl_custom_module_fields.json
> add responsive prop to image field

- snippets/man_gen/hubl_custom_module_fields.json
> Add font field snippet

- scripts/generate.js
Fixes format of snippets. This PR doesn't include an updated set of snippets yet.
> Fix snippet generation for block tags

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- snippets/man_gen/hubl_extras.json
I was originally planning to make some smaller updates for #73 but I wanted to split this out because I wanted to see about making the read me more concise.
Also adds changelog entry
> Update readme with recent changes

- README.md
> Re-org readme

- src/lib/constants.ts
- src/lib/tracking.ts
Adds toast on initial load to inform user about data collection.
> Telemetry prompt

- package.json
> Add regex for function creation visibility

- package.json
Updating the text that displays in authentication section when existing config is found.
> Auth section updates

- README.md
Updates the Welcome Screen of the extension in VS Code to new copy. Feature set of the extension will be made in another PR to merge separately in case CMS Dev Docs aren't updated by the pre-release date.
> Updates to welcome screen/repo readme for new version

- package.json
- src/lib/commands.ts
- src/lib/commands/remoteFs.ts
- src/lib/constants.ts
- src/lib/helpers.ts
Adds delete functionality on right click for remote FS.
Includes a check to make sure the action was intentional.
> Remote FS deletion

- package.json
- src/lib/commands/account.ts
- src/lib/constants.ts
> Add link to right click context on account to open design manager

- src/lib/commands/remoteFs.ts
- src/lib/providers/remoteFsProvider.ts
Minor changes based off feedback from UX office hours
> Copy changes

- package.json
- snippets/man_gen/hubl_blog_variables.json
- snippets/man_gen/hubl_color_and_font_settings.json
- snippets/man_gen/hubl_crm_object_dynamic_pages.json
- snippets/man_gen/hubl_email_variables.json
- snippets/man_gen/hubl_general_variables.json
- snippets/man_gen/hubl_hubdb_variables.json
- snippets/man_gen/hubl_in_app_editor_and_preview_variables.json
- snippets/man_gen/hubl_menu_node_variables.json
- snippets/man_gen/hubl_private_content_email_variables.json
- snippets/man_gen/hubl_request_variables.json
- snippets/man_gen/hubl_required_email_template_variables.json
- snippets/man_gen/hubl_required_page_template_variables.json
Closes #11 
Adds all the remaining variables as well as ran through the existing variables to ensure their accuracy.
> Update man gen hubl snippets

- package-lock.json
- package.json
- src/lib/panels/feedback.ts
- webview-ui/css/styles.css
Updating the feedback form to remove some of the scale for brevity.
> Updates to scale on Feedback Form

- package.json
> Update extension version

- .gitignore
adding to the gitignore so these don't get in the way of builds
> update gitignore for the built extension vsix files
